# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-11 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_urls', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7f51\u7ad9url')),
            ],
            options={
                'db_table': 'spider',
            },
        ),
    ]
